version: '3.8'

services:
  backend:
    build: ./backend
    container_name: fastapi_backend
    networks:
      - mlnet
    ports:
      - "8000:8000"
    volumes:
      - ./logs:/app/logs
    restart: always

  frontend:
    build: ./Streamlit
    container_name: streamlit_frontend
    depends_on:
      - backend
    networks:
      - mlnet
    ports:
      - "8501:8501"
    restart: always

  logstash:
    build:
      context: ./logstash
      dockerfile: Dockerfile
    container_name: logstash_container
    volumes:
      - ./logs:/logs
    restart: always

networks:
  mlnet:
    driver: bridge
